# Generated by Django 2.1.7 on 2019-03-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['user_name']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['title', 'post_date', 'blogger']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
